### PR TITLE
Eru poetry

### PR DESCRIPTION
**Pull request by MatthiasKuehneEllerhold**
See https://github.com/Ellerhold/fs2es-indexer/pull/16

### CODE REVIEW

**Comment by MatthiasKuehneEllerhold** [comment]
Ive looked at it and I'm not sure on how to proceed. I'd appreciate any help available @eru and others :)
Ive got two installation methods currently:

**Debian packaging**
We have a build system that build .deb packages so we can use this package internally on our servers. I've added the files (see DEBIAN/ and the fs2es-indexer.service file) to this repository. As you can see this is not very clever: it deploys the checkout to /opt/fs2es-indexer and then calls the `postinst` which just installs the dependencies via setuptools.

This is not debian at all! 
A little better: the dependencies should be in the project itself and not installed during installation.
Far better (the debian way): each dependency should be packaged on their own. But debian bullseye only has v7 of the ES-lib in their repository. Even bullseye-backports only has 7.16! But for ES v8 we need the v8 lib.

**Just checkout and go**
This method is for people that just want to checkout and run the indexer. Ive had people running this on non-debian machines like a consumer NAS and on other distributions like RHEL.


So thats the status quo.


So what I've read and found is that even the correct "debian way" is not really the way python develops tend to go themselves. It seems like publishing via PyPi is way more common than building .deb packages.

So my question to @eru and others is this: 
If I use poetry, can I transform this project so that I can publish to PyPi and satisfy the people that just want to install and run it?
Do people need poetry on their machines to be able to run it then? Or is it just my build machine that needs poetry? I guess they'll need pip, but not setuptools anymore - correct?

For the debian package: poetry can build a .whl file. This file can be installed via pip install (the target machine would therefor need pip instead of setuptools). This seems like an improvment to now.

What do you think ?

**Comment by eru** [comment]
@MatthiasKuehneEllerhold 

>If I use poetry, can I transform this project so that I can publish to PyPi and satisfy the people that just want to install and run it?
Yes. You can publish packages to pypi with the `poetry publish` command.
The following part of `pyproject.toml` is handled well by poetry, so if you build the package from my PR and install it with pip, you are probably ready to run it as a command.

```
[tool.poetry.scripts]    
fs2es-indexer = "fs2es_indexer.fs2es-indexer:main"
```

I think the following steps will build the package and install it locally to see if it works. (I am sorry if there are any mistakes as I am writing this without checking it in my environment)

```
$ poetry build
$ pip install dist/fs2es_indexer-0.4.0-py3-none-any.whl
$ fs2es-indexer --help
````

>Do people need poetry on their machines to be able to run it then? Or is it just my build machine that needs poetry? I guess they'll need pip, but not setuptools anymore - correct?

Yes. Only the pip command is required.

**Comment by MatthiasKuehneEllerhold** [comment]
As you can see in the `build-package-directory.sh` Ive added building .whl files for all dependencies. I can then install them offline (see `DEBIAN/postinst`). `poetry build` only creates a `.whl` for my main project, but not for the dependencies!

This works great on debian bullseye, but on buster this fails with:
```
$ pip3 wheel . -w wheels
Processing /.../fs2es-indexer-0.5.0-alpha2/fs2es-indexer-0.5.0-alpha2
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-mvxxkuu_/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-mvxxkuu_/
```

Sadly my build server is still buster and cant be changed atm. Do you have any idea why this fails ?

**Comment by MatthiasKuehneEllerhold** [comment]
Poetry build crashes here too: 
```bash
$ ./publish-pypi.sh 0.5.0-alpha4
There are 2 files ready for publishing. Build anyway? (yes/no) [no] yes
Building fs2es-indexer (0.5.0-alpha4)
  - Building sdist
  - Built fs2es-indexer-0.5.0a4.tar.gz
  - Building wheel
  - Built fs2es_indexer-0.5.0a4-py3-none-any.whl


  TypeError

  entry_points() got an unexpected keyword argument 'group'

  at /usr/local/lib/python3.7/dist-packages/keyring/backend.py:195 in _load_plugins
      191│     of the plugin at initialization time.
      192│
      193│     `initialize_func` is optional, but will be invoked if callable.
      194│     """
    → 195│     for ep in metadata.entry_points(group='keyring.backends'):
      196│         try:
      197│             log.debug('Loading %s', ep.name)
      198│             init_func = ep.load()
      199│             if callable(init_func):
```

I have to put a pin on that atm. My time is sadly running out.

**Comment by MatthiasKuehneEllerhold** [comment]
Sorry I have to close this.

Ive gone back to just pip installing the dependencies because this is much easier for me while coding / debugging etc.

Ive got too little time to do this "right" at the moment. Thanks for your contributions and sorry that I wont use it!

**Pull request closed without merging**
